// Code generated by github.com/doordash-oss/oapi-codegen-dd/v3. DO NOT EDIT.

package apiclient

import (
	"context"
	"encoding/json/v2"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	// GetAPIV1SessionsIDWatch Watch session events
	GetAPIV1SessionsIDWatch(ctx context.Context, options *GetAPIV1SessionsIDWatchRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetAPIV1SessionsIDWatchResponse, error)
	GetAPIV1SessionsIDWatchStream(ctx context.Context, options *GetAPIV1SessionsIDWatchRequestOptions, reqEditors ...runtime.RequestEditorFn) (*runtime.Stream[[]byte], error)
}

// GetAPIV1SessionsIDWatch Watch session events
func (c *Client) GetAPIV1SessionsIDWatch(ctx context.Context, options *GetAPIV1SessionsIDWatchRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetAPIV1SessionsIDWatchResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/sessions/{id}/watch",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetAPIV1SessionsIDWatchResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetAPIV1SessionsIDWatchErrorResponse)
			// Handle empty error response body gracefully - skip unmarshal if no content
			if len(bodyBytes) > 0 {
				if err = json.Unmarshal(bodyBytes, target); err != nil {
					return nil, &runtime.ResponseDecodeError{
						StatusCode:    resp.StatusCode,
						ContentType:   resp.Headers.Get("Content-Type"),
						ContentLength: len(bodyBytes),
						TargetType:    "GetAPIV1SessionsIDWatchErrorResponse",
						Body:          bodyBytes,
						Err:           err,
					}
				}
			}
			// Return error with (possibly empty) target
			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		result := GetAPIV1SessionsIDWatchResponse(bodyBytes)
		return &result, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/sessions/{id}/watch")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)

// GetAPIV1SessionsIDWatchRequestOptions is the options needed to make a request to GetAPIV1SessionsIDWatch.
type GetAPIV1SessionsIDWatchRequestOptions struct {
	PathParams *GetAPIV1SessionsIDWatchPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetAPIV1SessionsIDWatchRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetAPIV1SessionsIDWatchRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetAPIV1SessionsIDWatchRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetAPIV1SessionsIDWatchRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetAPIV1SessionsIDWatchRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetAPIV1SessionsIDWatchStream consumes the text/event-stream response of
// GetAPIV1SessionsIDWatch as a live stream. The body is never buffered, so this works against
// an endless stream. The caller must Close the returned stream.
func (c *Client) GetAPIV1SessionsIDWatchStream(ctx context.Context, options *GetAPIV1SessionsIDWatchRequestOptions, reqEditors ...runtime.RequestEditorFn) (*runtime.Stream[[]byte], error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/sessions/{id}/watch",
		Method:     "GET",
		Stream:     "text/event-stream",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/sessions/{id}/watch")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	if resp.StatusCode != 200 {

		if resp.Raw != nil && resp.Raw.Body != nil {
			_ = resp.Raw.Body.Close()
		}
		target := new(GetAPIV1SessionsIDWatchErrorResponse)
		if len(resp.Content) > 0 {
			if err = json.Unmarshal(resp.Content, target); err != nil {
				return nil, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(resp.Content),
					TargetType:    "GetAPIV1SessionsIDWatchErrorResponse",
					Body:          resp.Content,
					Err:           err,
				}
			}
		}
		if errTarget, ok := any(*target).(error); ok {
			return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
		}
		return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
			runtime.WithStatusCode(resp.StatusCode))
	}

	// Buffered at the streaming status means the server answered with another
	// content type. Say so rather than return a stream that yields nothing.
	if !resp.Streaming {
		return nil, runtime.NewClientAPIError(
			fmt.Errorf("expected a text/event-stream stream, got Content-Type %q", resp.Headers.Get("Content-Type")),
			runtime.WithStatusCode(resp.StatusCode))
	}

	return runtime.NewEventStream[[]byte](resp.Raw), nil
}

type GetAPIV1SessionsIDWatchPath struct {
	// ID Session ID
	ID string `json:"id" validate:"required"`
}

func (g GetAPIV1SessionsIDWatchPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetAPIV1SessionsIDWatchResponse = []byte

type GetAPIV1SessionsIDWatchErrorResponse = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON403 = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON404 = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON409 = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON422 = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON500 = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON501 = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON502 = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON503 = APIErrorResponse

type GetAPIV1SessionsIDWatchErrorResponseJSON504 = APIErrorResponse

type APIErrorResponse struct {
	Code              *string `json:"code,omitempty"`
	CurrentGeneration *int64  `json:"current_generation,omitempty"`
	CurrentManifestID *string `json:"current_manifest_id,omitempty"`
	CurrentReceipt    *string `json:"current_receipt,omitempty"`
	ErrorData         string  `json:"error" validate:"required"`
	UploadOffset      *int64  `json:"upload_offset,omitempty"`
}

func (a APIErrorResponse) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}

func (s APIErrorResponse) Error() string {
	return "unmapped client error"
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
