package parser

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestOpenCodeV2CapturedWorkflow(t *testing.T) {
	// Generated by OpenCode 1.18.25's /api/session v2 API, with scratch paths
	// replaced. This fixture is producer output, not assembled by the simulator.
	raw, err := os.ReadFile("testdata/opencode_v2/messages.json")
	require.NoError(t, err)
	var rows []struct {
		ID      string         `json:"id"`
		Type    string         `json:"type"`
		Seq     int64          `json:"seq"`
		Created int64          `json:"time_created"`
		Updated int64          `json:"time_updated"`
		Data    jsontext.Value `json:"data"`
	}
	require.NoError(t, json.Unmarshal(raw, &rows))
	path, seed, writer := newTestDB(t)
	seed.AddProject("project-a", "/workspace/project-a")
	seed.AddSession("ses_captured", "project-a", "", "Count lines", 1788899250985, 1788899253026)
	_, err = writer.Exec(openCodeV2TestSchema)
	require.NoError(t, err)
	for _, row := range rows {
		_, err = writer.Exec(`INSERT INTO session_message VALUES (?, 'ses_captured', ?, ?, ?, ?, ?)`, row.ID, row.Type, row.Seq, row.Created, row.Updated, string(row.Data))
		require.NoError(t, err)
	}
	sess, msgs, err := parseOpenCodeDBSession(path, "ses_captured", "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess)
	require.Len(t, msgs, 4)
	assert.Equal(t, 1, sess.UserMessageCount)
	assert.Equal(t, "Read input.txt using the read tool. Reply with the three words in order and the number of lines. Do not edit files or run other commands.", msgs[0].Content)
	assert.True(t, msgs[1].HasThinking)
	require.Len(t, msgs[1].ToolCalls, 1)
	call := msgs[1].ToolCalls[0]
	assert.Equal(t, "read", call.ToolName)
	assert.JSONEq(t, `{"path":"input.txt"}`, call.InputJSON)
	require.Len(t, call.ResultEvents, 1)
	assert.Equal(t, "alpha\nbeta\ngamma\n", call.ResultEvents[0].Content)
	assert.True(t, msgs[2].IsSystem)
	assert.Equal(t, "The three words in order are: **alpha**, **beta**, **gamma**.\n\nThe file has **3 lines**.", msgs[3].Content)
	assert.Equal(t, "big-pickle", msgs[3].Model)
	assert.Equal(t, 25, msgs[3].OutputTokens)
	assert.Equal(t, 3487, msgs[3].ContextTokens)
}

// Projection schema from anomalyco/opencode dff8fbc149fb, core/src/session/sql.ts.
// The producer retains session/message/part for v1 sessions in the same DB.
const openCodeV2TestSchema = `CREATE TABLE session_message (
 id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES session(id) ON DELETE CASCADE,
 type TEXT NOT NULL, seq INTEGER NOT NULL, time_created INTEGER NOT NULL,
 time_updated INTEGER NOT NULL, data TEXT NOT NULL
);
CREATE UNIQUE INDEX session_message_session_seq_idx ON session_message(session_id, seq);
CREATE INDEX session_message_session_type_seq_idx ON session_message(session_id, type, seq);
CREATE INDEX session_message_session_time_created_id_idx ON session_message(session_id, time_created, id);
CREATE INDEX session_message_time_created_idx ON session_message(time_created);`

func TestOpenCodeV2Projection(t *testing.T) {
	path, seed, writer := newTestDB(t)
	t.Cleanup(func() { writer.Close() })
	seed.AddProject("project-a", "/workspace/project-a")
	seed.AddSession("ses_v2", "project-a", "ses_parent", "", 1700000000000, 1700000060000)
	_, err := writer.Exec(openCodeV2TestSchema)
	require.NoError(t, err)
	// IDs and timestamps deliberately disagree with event sequence order.
	_, err = writer.Exec(`INSERT INTO session_message VALUES
 ('msg_a', 'ses_v2', 'assistant', 20, 1700000000000, 1700000000000,
 '{"agent":"build","model":{"id":"gpt-5.4","providerID":"openai"},"time":{"created":1700000000000},"content":[{"type":"text","id":"txt_a","text":"Draft"}]}'),
 ('msg_z', 'ses_v2', 'user', 10, 1700000000100, 1700000000100,
 '{"text":"Check the query","files":[],"agents":[],"time":{"created":1700000000100}}')`)
	require.NoError(t, err)
	sess, msgs, err := parseOpenCodeDBSession(path, "ses_v2", "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess, "v2 conversation must be imported")
	require.Len(t, msgs, 2)
	assert.Equal(t, "Check the query", msgs[0].Content)
	assert.Equal(t, "Draft", msgs[1].Content)
	assert.Equal(t, "opencode:ses_parent", sess.ParentSessionID)
	assert.Equal(t, "Check the query", sess.FirstMessage)
	assert.Equal(t, "/workspace/project-a", sess.Cwd)
	before, err := ListOpenCodeSessionMeta(path)
	require.NoError(t, err)

	// Text.Ended, Tool.Success and Step.Ended update a projection in place.
	// A high session timestamp must not hide this child-only update.
	_, err = writer.Exec(`UPDATE session_message SET time_updated = 1700000001000, data =
 '{"agent":"build","model":{"id":"gpt-5.4","providerID":"openai"},
 "time":{"created":1700000000000,"completed":1700000001000},
 "tokens":{"input":100,"output":20,"reasoning":5,"cache":{"read":30,"write":0}},
 "content":[{"type":"reasoning","id":"z","text":"Inspect the plan"},
 {"type":"tool","id":"call_a","name":"bash","time":{"created":1700000000000,"completed":1700000000900},
 "state":{"status":"completed","input":{"command":"explain query"},"structured":{},"content":[{"type":"text","text":"Index scan"}]}},
 {"type":"text","id":"a","text":"Use the index"}]}' WHERE id = 'msg_a'`)
	require.NoError(t, err)
	after, err := ListOpenCodeSessionMeta(path)
	require.NoError(t, err)
	require.Len(t, after, 1)
	assert.Equal(t, before[0].FileMtime, after[0].FileMtime)
	assert.NotEqual(t, before[0].ChildDigest, after[0].ChildDigest)
	mtime, digest, composite, err := openCodeSessionCompositeMtime(writer, path, "ses_v2")
	require.NoError(t, err)
	assert.True(t, composite)
	assert.Equal(t, after[0].ChildDigest, digest)
	assert.Equal(t, after[0].FileMtime, mtime*1_000_000)
	sess, msgs, err = parseOpenCodeDBSession(path, "ses_v2", "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess)
	require.Len(t, msgs, 2)
	assert.Equal(t, "[Thinking]\nInspect the plan\n[/Thinking]\nUse the index", msgs[1].Content)
	assert.True(t, msgs[1].HasThinking)
	assert.Equal(t, "gpt-5.4", msgs[1].Model)
	assert.JSONEq(t, `{"input_tokens":100,"output_tokens":20,"cache_read_input_tokens":30,"cache_creation_input_tokens":0}`, string(msgs[1].TokenUsage))
	require.Len(t, msgs[1].ToolCalls, 1)
	call := msgs[1].ToolCalls[0]
	assert.Equal(t, "call_a", call.ToolUseID)
	assert.Equal(t, "bash", call.ToolName)
	assert.JSONEq(t, `{"command":"explain query"}`, call.InputJSON)
	require.Len(t, call.ResultEvents, 1)
	assert.Equal(t, "completed", call.ResultEvents[0].Status)
	assert.Equal(t, "Index scan", call.ResultEvents[0].Content)

	// Revert.Committed removes later projection rows without lowering session time.
	_, err = writer.Exec(`DELETE FROM session_message WHERE session_id = 'ses_v2' AND seq > 10`)
	require.NoError(t, err)
	reverted, err := ListOpenCodeSessionMeta(path)
	require.NoError(t, err)
	assert.NotEqual(t, after[0].ChildDigest, reverted[0].ChildDigest)
	_, msgs, err = parseOpenCodeDBSession(path, "ses_v2", "host-a")
	require.NoError(t, err)
	require.Len(t, msgs, 1)
	assert.Equal(t, "Check the query", msgs[0].Content)
}

func TestOpenCodeV2MixedDatabase(t *testing.T) {
	path, seed, writer := newTestDB(t)
	_, err := writer.Exec(openCodeV2TestSchema)
	require.NoError(t, err)
	seed.AddProject("project-a", "/workspace/project-a")
	for _, id := range []string{"ses_v1", "ses_v2"} {
		seed.AddSession(id, "project-a", "", "Conversation", 1700000000000, 1700000001000)
		seed.AddMessage("msg_"+id, id, 1700000000000, 1700000000000, `{"role":"user"}`)
		seed.AddPart("prt_"+id, "msg_"+id, id, 1700000000000, 1700000000000, `{"type":"text","text":"Legacy conversation"}`)
	}
	_, err = writer.Exec(`INSERT INTO session_message VALUES ('msg_v2', 'ses_v2', 'user', 1, 1700000000000, 1700000000000, '{"text":"Projected conversation"}')`)
	require.NoError(t, err)
	for _, tc := range []struct{ id, text string }{{"ses_v1", "Legacy conversation"}, {"ses_v2", "Projected conversation"}} {
		t.Run(tc.id, func(t *testing.T) {
			assert.True(t, OpenCodeSQLiteSessionExists(path, tc.id))
			_, msgs, err := parseOpenCodeDBSession(path, tc.id, "host-a")
			require.NoError(t, err)
			require.Len(t, msgs, 1)
			assert.Equal(t, tc.text, msgs[0].Content)
		})
	}
}

func TestOpenCodeV2ToolStates(t *testing.T) {
	for _, tc := range []struct{ name, tool, state, status, text string }{
		{"structured", "custom", `{"status":"completed","input":{},"structured":{"content":[1,2],"exit":"other"},"content":[{"type":"text","text":"Done"}]}`, "completed", "Done"},
		{"pending", "bash", `{"status":"pending","input":"{\"command\":"}`, "", ""},
		{"running", "bash", `{"status":"running","input":{"command":"query"},"structured":{},"content":[]}`, "", ""},
		{"failed", "read", `{"status":"error","input":{"path":"missing.txt"},"structured":{},"content":[],"error":{"type":"unknown","message":"File missing"}}`, "errored", "File missing"},
		{"exit", "bash", `{"status":"completed","input":{"command":"false"},"structured":{"exit":1},"content":[{"type":"text","text":"Command exited with code 1."}]}`, "errored", "Command exited with code 1."},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path, seed, writer := newTestDB(t)
			seed.AddProject("project-a", "/workspace/project-a")
			seed.AddSession("ses_a", "project-a", "", "", 1700000000000, 1700000001000)
			_, err := writer.Exec(openCodeV2TestSchema)
			require.NoError(t, err)
			_, err = writer.Exec(`INSERT INTO session_message VALUES ('msg_a', 'ses_a', 'assistant', 1, 1700000000000, 1700000001000, ?)`,
				fmt.Sprintf(`{"content":[{"type":"tool","id":"call_a","name":%q,"state":%s,"time":{"created":1700000000000,"completed":1700000001000}}]}`, tc.tool, tc.state))
			require.NoError(t, err)
			_, msgs, err := parseOpenCodeDBSession(path, "ses_a", "host-a")
			require.NoError(t, err)
			require.Len(t, msgs, 1)
			require.Len(t, msgs[0].ToolCalls, 1)
			call := msgs[0].ToolCalls[0]
			if tc.status == "" {
				assert.Empty(t, call.ResultEvents)
			} else {
				require.Len(t, call.ResultEvents, 1)
				assert.Equal(t, tc.status, call.ResultEvents[0].Status)
				assert.Equal(t, tc.text, call.ResultEvents[0].Content)
			}
		})
	}
}

func TestOpenCodeV2MessageKinds(t *testing.T) {
	for _, tc := range []struct {
		kind, data, content          string
		system, tool, usage, invalid bool
	}{
		{kind: "system", data: `{"text":"System context"}`, content: "System context", system: true},
		{kind: "synthetic", data: `{"text":"Injected context"}`, content: "Injected context", system: true},
		{kind: "compaction", data: `{"summary":"Earlier work summary","recent":"recent context","reason":"auto"}`, content: "Earlier work summary", system: true},
		{kind: "shell", data: `{"command":"echo hello","callID":"call_shell","output":"hello\n","time":{"created":1700000000000,"completed":1700000001000}}`, content: "echo hello", tool: true},
		{kind: "assistant", data: `{"model":{"id":"gpt-5.4"},"content":[],"tokens":{"input":0,"output":0,"reasoning":0,"cache":{"read":0,"write":0}}}`, usage: true},
		{kind: "user", data: `{"text":`, invalid: true},
	} {
		t.Run(tc.kind, func(t *testing.T) {
			path, seed, writer := newTestDB(t)
			seed.AddProject("project-a", "/workspace/project-a")
			seed.AddSession("ses_a", "project-a", "", "", 1700000000000, 1700000001000)
			_, err := writer.Exec(openCodeV2TestSchema)
			require.NoError(t, err)
			_, err = writer.Exec(`INSERT INTO session_message VALUES ('msg_a', 'ses_a', ?, 1, 1700000000000, 1700000001000, ?)`, tc.kind, tc.data)
			require.NoError(t, err)
			sess, msgs, err := parseOpenCodeDBSession(path, "ses_a", "host-a")
			if tc.invalid {
				require.Error(t, err)
				assert.Nil(t, sess)
				return
			}
			require.NoError(t, err)
			require.NotNil(t, sess)
			require.Len(t, msgs, 1)
			assert.Equal(t, tc.content, msgs[0].Content)
			assert.Equal(t, tc.system, msgs[0].IsSystem)
			assert.Equal(t, tc.tool, msgs[0].HasToolUse)
			if tc.system {
				assert.Zero(t, sess.UserMessageCount)
			}
			if tc.tool {
				require.Len(t, msgs[0].ToolCalls, 1)
				assert.JSONEq(t, `{"command":"echo hello"}`, msgs[0].ToolCalls[0].InputJSON)
				require.Len(t, msgs[0].ToolCalls[0].ResultEvents, 1)
				assert.Equal(t, "hello\n", msgs[0].ToolCalls[0].ResultEvents[0].Content)
			}
			if tc.usage {
				assert.Equal(t, "gpt-5.4", msgs[0].Model)
				assert.True(t, msgs[0].HasContextTokens)
				assert.True(t, msgs[0].HasOutputTokens)
				assert.JSONEq(t, `{"input_tokens":0,"output_tokens":0,"cache_read_input_tokens":0,"cache_creation_input_tokens":0}`, string(msgs[0].TokenUsage))
			}
		})
	}
}
